# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and package-lock.json (if available) for dependency installation
COPY package*.json ./

# Install dependencies without running any scripts to avoid potential issues
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY . .

# Expose port if needed (not required for stdio transport, but in case)
# EXPOSE 3000

# Command to run the MCP server using stdio transport
CMD ["npm", "start"]
